Update husky only run in staged files and fix files
Signed-off-by: Axel <axel@io.builders>

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,5 +1,97 @@
-#!/usr/bin/env sh
+#!/bin/bash
 . "$(dirname -- "$0")/_/husky.sh"
 
+checkPrettier () {
+    npm run prettierCheck "$1" 
 
-npm run pre-commit
+}
+
+checkLinter(){
+    npm run lint
+    if [ $? -eq 0 ]; then
+        echo "\t\033[32mLint Passed: $1\033[0m"
+    else
+        echo "\t\033[41mLint Failed: $1\033[0m"
+        echo "Code style issues found in the above file(s). Forgot to run lint?"  
+        exit 1;
+    fi
+}
+
+checkSolhint(){
+    npm run lintFile:sol "$1"
+    if [ $? -eq 0 ]; then
+        echo "\t\033[32mSolhint Passed: $1\033[0m"
+    else
+        echo "\t\033[41mSolhint Failed: $1\033[0m"
+        echo "Code style issues found in the above file(s). Forgot to run solhint?"  
+        exit 1;
+    fi
+}
+
+CLI_STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM ./cli/)
+CONTRACTS_STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM ./contracts/)
+SDK_STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM ./sdk/)
+WEB_STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM ./web/)
+
+if ( [ "$CLI_STAGED_FILES" = "" ] && 
+    [ "$CONTRACTS_STAGED_FILES" = "" ] && 
+    [ "$SDK_STAGED_FILES" = "" ] && 
+    [ "$WEB_STAGED_FILES" = "" ] ); then
+  exit 0
+fi
+
+echo "\nValidating Prettier & Linting:\n"
+
+for FILE in $CLI_STAGED_FILES
+do
+
+    FILE_VALIDATE="${FILE#*/}"
+
+    cd cli
+
+    checkPrettier $FILE_VALIDATE 
+    checkLinter $FILE_VALIDATE
+
+    cd ..
+done
+
+for FILE in $CONTRACTS_STAGED_FILES
+do
+    FILE_VALIDATE="${FILE#*/}"
+    filename=$(basename -- "$FILE")
+    extension="${filename##*.}"
+
+    cd contracts
+    checkPrettier $FILE_VALIDATE
+    
+    if [ "$extension" = 'sol' ]; then
+        checkSolhint $FILE_VALIDATE
+    else
+        checkLinter $FILE_VALIDATE
+    fi
+    cd ..
+done
+
+for FILE in $SDK_STAGED_FILES
+do
+    FILE_VALIDATE="${FILE#*/}"
+
+    cd sdk
+    checkPrettier $FILE_VALIDATE
+    checkLinter $FILE_VALIDATE
+    
+    cd ..
+done
+
+for FILE in $WEB_STAGED_FILES
+do
+    FILE_VALIDATE="${FILE#*/}"
+
+    cd web
+    checkPrettier $FILE_VALIDATE
+    checkLinter $FILE_VALIDATE
+    cd ..
+done
+
+exit $?
+
