fix: check all the secrets without displaying them
Signed-off-by: Alberto Molina <alberto@io.builders>

diff --git a/.github/workflows/test.workflow.yml b/.github/workflows/test.workflow.yml
--- a/.github/workflows/test.workflow.yml
+++ b/.github/workflows/test.workflow.yml
@@ -14,21 +14,55 @@ jobs:
       contents: read
     
     steps:
-      - name: Test secrets
+      - name: Verify specific secrets are available
         run: |
-          touch .env
-          # Making API call to fetch secrets
-          echo "API_ACCESS_TOKEN_1=${{ secrets.API_ACCESS_TOKEN_1 }}"
-          echo "API_ACCESS_TOKEN_2=${{ secrets.API_ACCESS_TOKEN_2 }}"
-          echo "CLIENT_PRIVATE_KEY_ECDSA=${{ secrets.CLIENT_PRIVATE_KEY_ECDSA }}"
-          echo "CLIENT_PUBLIC_KEY_ECDSA=${{ secrets.CLIENT_PUBLIC_KEY_ECDSA }}" 
-          echo "CLIENT_EVM_ADDRESS_ECDSA=${{ secrets.CLIENT_EVM_ADDRESS_ECDSA }}"
-          echo "CLIENT_ACCOUNT_ID_ECDSA=${{ secrets.CLIENT_ACCOUNT_ID_ECDSA }}"
-          echo "CLIENT_PRIVATE_KEY_ED25519=${{ secrets.CLIENT_PRIVATE_KEY_ED25519 }}"
-          echo "CLIENT_PUBLIC_KEY_ED25519=${{ secrets.CLIENT_PUBLIC_KEY_ED25519 }}"
-          echo "CLIENT_EVM_ADDRESS_ED25519=${{ secrets.CLIENT_EVM_ADDRESS_ED25519 }}" 
-          echo "CLIENT_ACCOUNT_ID_ED25519=${{ secrets.CLIENT_ACCOUNT_ID_ED25519 }}" 
-          echo "CLIENT_PRIVATE_KEY_ED25519_2=${{ secrets.CLIENT_PRIVATE_KEY_ED25519_2 }}"
-          echo "CLIENT_PUBLIC_KEY_ED25519_2=${{ secrets.CLIENT_PUBLIC_KEY_ED25519_2 }}"
-          echo "CLIENT_EVM_ADDRESS_ED25519_2=${{ secrets.CLIENT_EVM_ADDRESS_ED25519_2 }}"
-          echo "CLIENT_ACCOUNT_ID_ED25519_2=${{ secrets.CLIENT_ACCOUNT_ID_ED25519_2 }}" 
+          echo "Verifying specific secrets..."
+          missing_secrets=false
+
+          check_secret() {
+            secret_name=$1
+            secret_value=${!secret_name}
+
+            if [ -z "$secret_value" ]; then
+              echo "Error: $secret_name is not set."
+              missing_secrets=true
+            else
+              echo "$secret_name is set."
+            fi
+          }
+
+          check_secret API_ACCESS_TOKEN_1
+          check_secret API_ACCESS_TOKEN_2
+          check_secret CLIENT_PRIVATE_KEY_ECDSA
+          check_secret CLIENT_PUBLIC_KEY_ECDSA
+          check_secret CLIENT_EVM_ADDRESS_ECDSA
+          check_secret CLIENT_ACCOUNT_ID_ECDSA
+          check_secret CLIENT_PRIVATE_KEY_ED25519
+          check_secret CLIENT_PUBLIC_KEY_ED25519
+          check_secret CLIENT_EVM_ADDRESS_ED25519
+          check_secret CLIENT_ACCOUNT_ID_ED25519
+          check_secret CLIENT_PRIVATE_KEY_ED25519_2
+          check_secret CLIENT_PUBLIC_KEY_ED25519_2
+          check_secret CLIENT_EVM_ADDRESS_ED25519_2
+          check_secret CLIENT_ACCOUNT_ID_ED25519_2
+
+          if [ "$missing_secrets" = true ]; then
+            exit 1
+          else
+            echo "All specified secrets are set."
+          fi
+        env:
+          API_ACCESS_TOKEN_1: ${{ secrets.API_ACCESS_TOKEN_1 }}
+          API_ACCESS_TOKEN_2: ${{ secrets.API_ACCESS_TOKEN_2 }}
+          CLIENT_PRIVATE_KEY_ECDSA: ${{ secrets.CLIENT_PRIVATE_KEY_ECDSA }}
+          CLIENT_PUBLIC_KEY_ECDSA: ${{ secrets.CLIENT_PUBLIC_KEY_ECDSA }}
+          CLIENT_EVM_ADDRESS_ECDSA: ${{ secrets.CLIENT_EVM_ADDRESS_ECDSA }}
+          CLIENT_ACCOUNT_ID_ECDSA: ${{ secrets.CLIENT_ACCOUNT_ID_ECDSA }}
+          CLIENT_PRIVATE_KEY_ED25519: ${{ secrets.CLIENT_PRIVATE_KEY_ED25519 }}
+          CLIENT_PUBLIC_KEY_ED25519: ${{ secrets.CLIENT_PUBLIC_KEY_ED25519 }}
+          CLIENT_EVM_ADDRESS_ED25519: ${{ secrets.CLIENT_EVM_ADDRESS_ED25519 }}
+          CLIENT_ACCOUNT_ID_ED25519: ${{ secrets.CLIENT_ACCOUNT_ID_ED25519 }}
+          CLIENT_PRIVATE_KEY_ED25519_2: ${{ secrets.CLIENT_PRIVATE_KEY_ED25519_2 }}
+          CLIENT_PUBLIC_KEY_ED25519_2: ${{ secrets.CLIENT_PUBLIC_KEY_ED25519_2 }}
+          CLIENT_EVM_ADDRESS_ED25519_2: ${{ secrets.CLIENT_EVM_ADDRESS_ED25519_2 }}
+          CLIENT_ACCOUNT_ID_ED25519_2: ${{ secrets.CLIENT_ACCOUNT_ID_ED25519_2 }}
